### ISSUE TITLE
[BUG] Action Message can't populate mustache expression values correctly 

### ISSUE THREAD

**Issue by Angie-Zhang** [opensearch-project/alerting-dashboards-plugin#333] opened 2022-09-26 16:17 UTC
**What is the bug?**
When creating actions for monitor, the message preview and message sent to webhook can't populate some mustache values correctly. 

**How can one reproduce the bug?**
Go through creating monitor -> trigger -> action
In preview:
1. we can't see value of trigger name and severity 
2. we can see period interval and unit
<img width="1008" alt="Screen Shot 2022-09-25 at 9 53 09 AM" src="https://user-images.githubusercontent.com/98716549/192325363-7d23cbcd-7715-42b4-a1f4-47b98eef54d6.png">
In the message received by webhook:
1. value of trigger name and severity poulate correctly
2. period interval and unit disappear
<img width="779" alt="Screen Shot 2022-09-25 at 9 53 17 AM" src="https://user-images.githubusercontent.com/98716549/192325383-c80a3bf9-3f87-4637-b44a-775cf4f40897.png">

**What is the expected behavior?**
Preview and message should display mustache values correctly.
**What is your host/environment?**
 - OS: Official Docker Image
 - Version 2.2; bug is also reported in 1.2

**Comment by AWSHurneyt** [comment] 2022-09-29 15:13
Related issue https://github.com/opensearch-project/alerting-dashboards-plugin/issues/152

**Comment by amsiglan** [comment] 2022-11-29 03:01
@AWSHurneyt Let's close this if it was fixed in #334

**Comment by AWSHurneyt** [comment] 2022-11-29 20:38
As mentioned in PR #334, there is still an issue that's causing the `ctx.monitor.schedule.period.interval` and `ctx.monitor.schedule.period.unit` to be blank when the notification is sent to the webhook. This is still under investigation. The message preview in the UI does show those values, suggesting this may be a backend issue.

**Comment by amsiglan** [comment] 2022-11-29 23:59
Okay, so only the first half is solved.

**Comment by AWSHurneyt** [comment] 2022-11-30 00:01
Correct.

**Comment by AWSHurneyt** [comment] 2022-12-07 20:25
> As mentioned in PR #334, there is still an issue that's causing the `ctx.monitor.schedule.period.interval` and `ctx.monitor.schedule.period.unit` to be blank when the notification is sent to the webhook. This is still under investigation. The message preview in the UI does show those values, suggesting this may be a backend issue.

Looks like the issue with the `schedule` was coming from the alerting backend. The `ctx` variable that's called in the action message body is generated in the monitor runner classes ([example](https://github.com/opensearch-project/alerting/blob/main/alerting/src/main/kotlin/org/opensearch/alerting/QueryLevelMonitorRunner.kt#L64)). The `TriggerExecutionContext` calls [monitor.asTemplateArg](https://github.com/opensearch-project/alerting/blob/main/alerting/src/main/kotlin/org/opensearch/alerting/script/TriggerExecutionContext.kt#L33) to created the `monitor` portion of the `ctx` variable; however, [Monitor::asTemplateArg](https://github.com/opensearch-project/common-utils/blob/main/src/main/kotlin/org/opensearch/commons/alerting/model/Monitor.kt#L124) doesn't actually return the monitor's `schedule` attribute. 

This problem relates to this backend issue https://github.com/opensearch-project/alerting/issues/200, which currently has PRs out with fixes for the backend.

@amsiglan, because there are PRs out to fix the backend, I think we can safely merge PR #334 to resolve the frontend portion of this issue. We can then close this issue as the other half of the problem is being tracked by the backend issue mentioned above.

**Comment by AWSHurneyt** [comment] 2022-12-08 17:59
Closing this frontend issue as PR #334 has been merged which addresses the frontend portion of this bug. The bug regarding the `interval` and `unit` `ctx` variables will be tracked in backend issue https://github.com/opensearch-project/alerting/issues/200. As mentioned above, there is currently a PR published to address that bug.

**Closed by AWSHurneyt** 2022-12-08 17:59 UTC
Labels: bug
