### ISSUE TITLE
Composite Monitor Notification Channel Dropdown Empty

### ISSUE THREAD

**Issue by skyallenm** [opensearch-project/alerting-dashboards-plugin#952] opened 2024-05-17 11:40 UTC
### Describe the bug

<img width="649" alt="moniter" src="https://github.com/opensearch-project/OpenSearch/assets/166394898/c7f23919-cb2c-4882-ad45-295fca37c2f3">

### Related component

Other

### To Reproduce

1. alert tab 
2. select composite monitor 
3. add trigger 
4. notification channel dropdown
5.

### Expected behavior

In composite monitor Notification channel  list should be display.

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by AWSHurneyt** [comment] 2024-05-23 19:01
@skyallenm and @KyongSik-Yoon Thanks for reporting this! We've tracked down the cause of this bug.

The following commit refactored the response object that gets returned by the API the Alerting UI uses to retrieve the channels.
https://github.com/opensearch-project/dashboards-notifications/commit/640535ee189fdf5449a87c70c956a9059864a9cb#diff-6495f662f11eb9366b891c845ddac043c64b34f3a11695a2bdb0d55f58169d4cR226

That commit was included in the 2.14 release, but the corresponding PR for the Alerting UI was not (PR https://github.com/opensearch-project/alerting-dashboards-plugin/pull/916). We're getting that fix backported so it's included in the next 2.14 patch.

In the meantime, a workaround would involve creating your monitor, and then using the UpdateMonitor API ([documentation link](https://opensearch.org/docs/latest/observing-your-data/alerting/api/#update-monitor)) to add an action to your trigger.

For now, I'll close this issue as the fix will be backported today; but feel free to comment if you have additional questions.

**Closed by AWSHurneyt** 2024-05-23 19:01 UTC
Labels: bug, untriaged
